spring:
  application:
    name: merchant-service
  datasource:
    url: jdbc:mysql://localhost:3308/merchant_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: cardValidationRequest:com.andrew.merchant_service.kafka.CardValidationRequest,kafkaLinkRequest:com.andrew.merchant_service.kafka.KafkaLinkRequest
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGateway
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: cardValidationResponse:com.andrew.merchant_service.kafka.CardValidationResponse,kafkaLinkResponse:com.andrew.merchant_service.kafka.KafkaLinkResponse
server:
  port: 8091