server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: merchant-service
          uri: lb://MERCHANT-SERVICE
          predicates:
            - Path=/api/v1/merchants/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
