spring:
  application:
    name: bank-service
  datasource:
    url: jdbc:mysql://localhost:3307/bank_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: cardValidationResponse:com.andrew.bank_service.kafka.CardValidationResponse,transactionResponse:com.andrew.bank_service.kafka.TransactionResponse
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGateway
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: cardValidationRequest:com.andrew.bank_service.kafka.CardValidationRequest,transactionRequest:com.andrew.bank_service.kafka.TransactionRequest
server:
  port: 8090